default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sammy
  password: password
  host: localhost

development:
  <<: *default
  database: shopping_cart_app_development

test:
  <<: *default
  database: shopping_cart_app_test

production:
  <<: *default
  database: shopping_cart_app_production
  username: shopping_cart_app
  password: <%= ENV['SHOPPING_CART_APP_DATABASE_PASSWORD'] %>
